#!/bin/bash

mariadbd --user=mysql --bootstrap <<EOF
USE mysql;
FLUSH PRIVILEGES;

DROP USER IF EXISTS ''@'localhost';
DROP DATABASE IF EXISTS test;

CREATE DATABASE IF NOT EXISTS $WP_DATABASE;
CREATE USER IF NOT EXISTS '$WP_DB_USER'@'%' IDENTIFIED BY '$WP_DB_PWD';
GRANT ALL PRIVILEGES ON $WP_DATABASE.* TO '$WP_DB_USER'@'%';

ALTER USER 'root'@'localhost' IDENTIFIED BY '$MARIADB_ROOT_PASSWORD';
FLUSH PRIVILEGES;
EOF

exec mariadbd